version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'production'
    labels:
      - 'prod-dependencies'
    allowed_updates:
      - match:
          update_type: "security"

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: master
    allow:
      - dependency-type: 'development'
    labels:
      - 'dev-dependencies'
      - 'automerge'
    allowed_updates:
      - match:
          update_type: "security"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    allowed_updates:
      - match:
          update_type: "security"
